### ISSUE TITLE
#012 "Arbitrage" - no access to the endpoint with maximum plan

### ISSUE THREAD

**Issue by iborzenkov** [iborzenkov/CryptoApisSdkLibrary#12]
### End Point 
Arbitrage
### URL
https://docs.cryptoapis.io/#arbitrage
### Description
I can’t test arbitrage endpoint. The error message is: "This endpoint has not been enabled for your package plan. Please contact us if you need this or upgrade your plan."

**Comment by Crypto-APIs** [comment]
Please, note that the package which you have subscribed to does not include Arbitrage software.

**Comment by iborzenkov** [comment]
(?) Could you tell me, please, what package includes arbitration?

**Comment by Crypto-APIs** [comment]
It's included in custom package only.

**Comment by iborzenkov** [comment]
(i) I couldn't test the endpoint. Tests are disabled.
