### ISSUE TITLE
#013 "BCH Block Hash" - the absence of parameters looks suspicious

### ISSUE THREAD

**Issue by iborzenkov** [iborzenkov/CryptoApisSdkLibrary#13]
### End Point 
BCH Block Hash
### URL
https://docs.cryptoapis.io/#-blockchain-block-hash-endpoint
### Description
Parameters
- strippedsize
- weight
are not described in the documentation and are not in the server responses for **TestNet**. However, in other tokens (LTC, BTC and BCH (MainNet)) they are. Looks suspicious.
### Details
**BCH TestNet:**
![013_2](https://user-images.githubusercontent.com/22618677/57381011-b67e8700-71dc-11e9-90fc-ac71de7798e2.png)

**BCH MainNet:**
![013_1](https://user-images.githubusercontent.com/22618677/57381016-bbdbd180-71dc-11e9-87eb-d041476dbb36.png)

**Comment by Crypto-APIs** [comment]
There are no strippedsize and weight parameters for BCH blocks.

**Comment by iborzenkov** [comment]
Please pay attention to the screenshots.
### **BCH MainNet**. There are parameters here.
![013_1](https://user-images.githubusercontent.com/22618677/57627135-f1603080-75c9-11e9-980f-4f9fff48fa99.png)
### **BCH TestNet**. There are no parameters here.
![013_2](https://user-images.githubusercontent.com/22618677/57627163-05a42d80-75ca-11e9-97aa-7751f41724a0.png)
(?) Is that right?

**Comment by Crypto-APIs** [comment]
These parameters come from the BCH node. They may be different for BCH MainNet and BCH TestNet.

**Comment by iborzenkov** [comment]
(+) Okay, I understand.
