### ISSUE TITLE
#014 "BTC Block Height" - typo in the text of the documentation

### ISSUE THREAD

**Issue by iborzenkov** [iborzenkov/CryptoApisSdkLibrary#14]
### End Point 
BTC Block Height
### URL
https://docs.cryptoapis.io/#btc-blockchain-block-height-endpoint
### Description
A typo in the text of the documentation. 
### Details
![014](https://user-images.githubusercontent.com/22618677/57180295-c5ea9100-6eb9-11e9-9fe2-992e8471c85c.png)

**Comment by Crypto-APIs** [comment]
We fixed it.

**Comment by iborzenkov** [comment]
(+) Done.
