### ISSUE TITLE
#015 "BCH Block Height" - typo in the text of the documentation

### ISSUE THREAD

**Issue by iborzenkov** [iborzenkov/CryptoApisSdkLibrary#15]
### End Point 
BCH Block Height
### URL
https://docs.cryptoapis.io/#bch-blockchain-block-height-endpoint
### Description
A typo in the text of the documentation. 
### Details
The problem same as #14

**Comment by Crypto-APIs** [comment]
We fixed it.

**Comment by iborzenkov** [comment]
(+) Done.
