### ISSUE TITLE
#016 "LTC Block Height" - typo in the text of the documentation

### ISSUE THREAD

**Issue by iborzenkov** [iborzenkov/CryptoApisSdkLibrary#16]
### End Point 
LTC Block Height
### URL
https://docs.cryptoapis.io/#ltc-blockchain-block-hash-endpoint
### Description
A typo in the text of the documentation. 
### Details
The problem same as #14

**Comment by Crypto-APIs** [comment]
We fixed it.

**Comment by iborzenkov** [comment]
(+) Done.
