### ISSUE TITLE
#017 "Multisig Address" - several parameters are missing from the documentation

### ISSUE THREAD

**Issue by iborzenkov** [iborzenkov/CryptoApisSdkLibrary#17]
### End Point 
Historical Data
### URL
https://docs.cryptoapis.io/#btc-address-multisig-info-endpoint
### Description
It is allowed to send parameters "**Skip**" and "**Limit**" to the server, but it are not specified in the documentation.

It is true for **BTC**, **BTH**, **LTC** endpoints.
### Details
![017](https://user-images.githubusercontent.com/22618677/57180373-95efbd80-6eba-11e9-973b-169b65a2756f.png)

**Comment by Crypto-APIs** [comment]
"LIMIT" has been added to our API documentation. Please, note that there is no "Skip" parameter for this endpoint.

**Comment by iborzenkov** [comment]
(+) Done
