### ISSUE TITLE
#018 "ETH Transactions by Address" - the number in server response is too large

### ISSUE THREAD

**Issue by iborzenkov** [iborzenkov/CryptoApisSdkLibrary#18]
### End Point 
ETH Transactions by Address
### URL
https://docs.cryptoapis.io/#eth-transactions-address-endpoint
### Description
Parameter "**Address**" = "**0xb794F5eA0ba39494cE839613fffBA74279579268**" 
It is not possible to deserialize the JSON into an object because the value of "**value**" field **(88750000000000000000000)** exceeds the size allowed for "int64" in .NET

**Comment by Crypto-APIs** [comment]
Please, try again with BigInteger library. This is the one we use.

**Comment by iborzenkov** [comment]
(+) Done
