### ISSUE TITLE
#019 "BCH Address Transactions" - not working endpoint

### ISSUE THREAD

**Issue by iborzenkov** [iborzenkov/CryptoApisSdkLibrary#19]
### End Point 
BCH Address Transactions
### URL
https://docs.cryptoapis.io/#bch-address-transactions-endpoint
### Description
Endpoint doesn't work.
Address: **"bitcoincash:pp8skudq3x5hzw8ew7vzsw8tn4k8wxsqsv0lt0mf3g"**
Network: **MainNet**
### Details
![019](https://user-images.githubusercontent.com/22618677/57180566-6e99f000-6ebc-11e9-8956-5bffa8b5807a.png)

**Comment by Crypto-APIs** [comment]
Please, note that BCH Mainnet is not synced yet.

**Comment by iborzenkov** [comment]
(+) Done

**Comment by Crypto-APIs** [comment]
We would like to inform you that BCH Mainnet is now synced.

**Comment by iborzenkov** [comment]
Exellent! I tested it.
