### ISSUE TITLE
#020 "LTC Multisig Address Endpoint" - "skip" parameter is ignored

### ISSUE THREAD

**Issue by iborzenkov** [iborzenkov/CryptoApisSdkLibrary#20]
### End Point 
LTC Multisig Address Endpoint
### URL
https://docs.cryptoapis.io/#ltc-address-multisig-info-endpoint
### Description
(-) “LTC”-endpoint **“Skip”** parameter is ignored. **"Limit"** parameter is working corrected.
(+) “BTC”-endpoint is correctly. 
(?) “BCH”-endpoint I couldn't check. I could not find the setting **“address”** with multisig address yet.
### Details
“Skip” = 0, “Limit” = 0 - it is a reference value
![020_1](https://user-images.githubusercontent.com/22618677/57180747-70fd4980-6ebe-11e9-9c15-bab01823a024.png)

“Skip” = 3, “Limit” = 0
Addresses are equals, skip ignored!
![020_2](https://user-images.githubusercontent.com/22618677/57180756-84101980-6ebe-11e9-8a63-a508d4af202e.png)

“Skip” = 2, “Limit” = 3
Addresses are equals, skip ignored! Limit applied correctly.
![020_3](https://user-images.githubusercontent.com/22618677/57180763-95592600-6ebe-11e9-9b95-a3b4885f3a8d.png)

**Comment by Crypto-APIs** [comment]
There is only "limit" parameter.

**Comment by iborzenkov** [comment]
(+) Done
