### ISSUE TITLE
#021 "ETH Transactions Index Endpoint by Index, Limit and Block Number" - "skip" parameter is not working properly

### ISSUE THREAD

**Issue by iborzenkov** [iborzenkov/CryptoApisSdkLibrary#21]
### End Point 
ETH Transactions Index Endpoint by Index, Limit and Block Number
### URL
https://docs.cryptoapis.io/#eth-transaction-index-endpoint-by-index-limit-block-number
### Description
Parameter **“Skip”** excludes items from the end of the list, not from the beginning. 
### Details
**“Skip”** = 0, a transaction with **Nonce=8230** is the first of list.
![021_1](https://user-images.githubusercontent.com/22618677/57180829-347e1d80-6ebf-11e9-90be-6bba45432ade.png)

**“Skip”** = 2, I expect the transaction with **Nonce=8230** will not be on the list. But it is there again the first!
![021_2](https://user-images.githubusercontent.com/22618677/57180836-4495fd00-6ebf-11e9-85d5-e2ad3a9e1bd9.png)

**Comment by Crypto-APIs** [comment]
Please, note that “Skip” parameter is related to the index of the transaction not to “Nonce”.

**Comment by iborzenkov** [comment]
(+) Done. Added sorting by "index" field".
