### ISSUE TITLE
#022 "ETH Transactions Index Endpoint by Index, Limit and Block Number" - "limit" parameter is not working properly

### ISSUE THREAD

**Issue by iborzenkov** [iborzenkov/CryptoApisSdkLibrary#22]
### End Point 
ETH Transactions Index Endpoint by Index, Limit and Block Number
### URL
https://docs.cryptoapis.io/#eth-transaction-index-endpoint-by-index-limit-block-number
### Description
Parameter “Limit” limits items from the begin of the list, not from the ending.
### Details
“Limit” = 100, a transaction with Nonce=750 is the 12th of list.
![022_1](https://user-images.githubusercontent.com/22618677/57180923-1f55be80-6ec0-11e9-8d8c-c2dd6f5ad16f.png)

“Limit” = 2, I expect the transaction with Nonce=750 will not be on the list. But it is there again the first!
![022_2](https://user-images.githubusercontent.com/22618677/57180933-3399bb80-6ec0-11e9-954e-9efc83b62c00.png)

**Comment by Crypto-APIs** [comment]
Please, note that “Limit” parameter shows the first n numbers of transactions included in the specified block, by Index not Nonce.

**Comment by iborzenkov** [comment]
(+) Done. Added sorting by "index" field".
