### ISSUE TITLE
#023 "Latest Data" - unexpected server response

### ISSUE THREAD

**Issue by iborzenkov** [iborzenkov/CryptoApisSdkLibrary#23]
### End Point 
Latest Data
### URL
https://docs.cryptoapis.io/#latest-data
### Description
If the parameter "**skip**" is too large, I expect to see an empty "**payload**" list in the response.
### Details
![023](https://user-images.githubusercontent.com/22618677/57306703-e151d800-7115-11e9-9195-3bc59312c312.png)

**Comment by Crypto-APIs** [comment]
There is no need of skip parameter. Therefore, we have removed it.

**Comment by iborzenkov** [comment]
(+) Done
