### ISSUE TITLE
#024 "Quotes Latest Data" server response does not match documentation

### ISSUE THREAD

**Issue by iborzenkov** [iborzenkov/CryptoApisSdkLibrary#24]
### End Point 
Quotes Latest Data
### URL
https://docs.cryptoapis.io/#quotes-latest-data
### Description
1. There is a parameter "eventTime" in the server response. But in documentation it named as "timeExchange"
![024_2](https://user-images.githubusercontent.com/22618677/57377856-086fde80-71d6-11e9-9762-b8721db9f72b.png)
2. There is no description of the parameter in the documentation
![024_1](https://user-images.githubusercontent.com/22618677/57377902-276e7080-71d6-11e9-955f-ba00f252fa90.png)

**Comment by Crypto-APIs** [comment]
“timeExchange“ parameter is now “eventTime“ in the server response sample. It has also been added to the table with output variables.

**Comment by iborzenkov** [comment]
(+) Done
