### ISSUE TITLE
#025 "Quotes Latest Data" - "skip" parameter is not working properly

### ISSUE THREAD

**Issue by iborzenkov** [iborzenkov/CryptoApisSdkLibrary#25]
### End Point 
Quotes Latest Data
### URL
https://docs.cryptoapis.io/#quotes-latest-data
### Description
Parameter **“Skip”** excludes items from the end of the list, not from the beginning. 
### Details
**“Skip”** = 0, a transaction with **Amount=167.92935408** is the first of list.
![025_1](https://user-images.githubusercontent.com/22618677/57378556-98faee80-71d7-11e9-88f9-b4158445cc5f.png)

**“Skip”** = 2, I expect the transaction with **Amount=167.92935408** will not be on the list. But it is there again the first!
![025_2](https://user-images.githubusercontent.com/22618677/57378580-a7e1a100-71d7-11e9-882c-5f3382daec0e.png)

**Comment by Crypto-APIs** [comment]
There is no need of skip parameter. Therefore, we have removed it.

**Comment by iborzenkov** [comment]
(+) Done. I updated the C# SDK.
