### ISSUE TITLE
#026 "Quotes Historical Data" - "skip" parameter is not working properly

### ISSUE THREAD

**Issue by iborzenkov** [iborzenkov/CryptoApisSdkLibrary#26]
### End Point 
Quotes Historical Data
### URL
https://docs.cryptoapis.io/#quotes-historical-data
### Description
Parameter **“Skip”** excludes items not from the beginning. 
### Details
**“Skip”** = 0, a record with **Amount=18.66007842** is the third of list.
![026_1](https://user-images.githubusercontent.com/22618677/57379345-54705280-71d9-11e9-9884-1a727d848156.png)

**“Skip”** = 2, I expect the transaction with **Amount=18.66007842** will be the first of list. But it's not there!
![026_2](https://user-images.githubusercontent.com/22618677/57379358-59cd9d00-71d9-11e9-832d-d1d2ffb84992.png)

**Comment by Crypto-APIs** [comment]
We have edited the description of the end point. It is now precise.

**Comment by iborzenkov** [comment]
(+) Done
