### ISSUE TITLE
#028 "Multisig Address" - numeric values are described by strings

### ISSUE THREAD

**Issue by iborzenkov** [iborzenkov/CryptoApisSdkLibrary#28]
### End Point 
- Address
- Multisig Address

for BTC, BCH and LTC too
### URL
https://docs.cryptoapis.io/?shell#btc-address-info-endpoint
https://docs.cryptoapis.io/?shell#btc-address-multisig-info-endpoint
### Description
Parameters "**totalSpent**", "**totalReceived**" and "**balance**" are numeric. But in JSON response they are strings. 
Is that correct?

### Details
![028](https://user-images.githubusercontent.com/22618677/58103121-04e84880-7c15-11e9-906c-f2868487fc01.png)

**Comment by Crypto-APIs** [comment]
It is a string.

**Comment by iborzenkov** [comment]
(+) Okay, I fixed the "string" in unit-tests.
