### ISSUE TITLE
#029 "Webhook Notification" /  "Create New Block Webhook" (BCH) - Internal Server Error

### ISSUE THREAD

**Issue by iborzenkov** [iborzenkov/CryptoApisSdkLibrary#29]
### End Point 
"Webhook Notification" /  "Create New Block Webhook" (BCH: mainnet and testnet)
### URL
https://docs.cryptoapis.io/?http#bch-webhooks-create-new-block-webhook-endpoint
### Description
The endpoint does not working: "Internal Server Error"

### Details
![3](https://user-images.githubusercontent.com/22618677/58103248-40831280-7c15-11e9-855e-5ff6008953ff.png)
![4](https://user-images.githubusercontent.com/22618677/58103252-42e56c80-7c15-11e9-83b9-639602ca5482.png)

**Comment by Crypto-APIs** [comment]
We fixed it.

**Comment by iborzenkov** [comment]
(+) Done
