### ISSUE TITLE
#030 "Webhook Notification" / "Create Confirmed Transaction WebHook" (BCH) - Internal Server Error #29

### ISSUE THREAD

**Issue by iborzenkov** [iborzenkov/CryptoApisSdkLibrary#30]
### End Point 
"Webhook Notification" /  "Create Confirmed Transaction WebHook" (BCH: mainnet and testnet)
### URL
https://docs.cryptoapis.io/?http#bch-webhooks-create-confirmed-transaction-webhook-endpoint
### Description
The endpoint does not working: "Internal Server Error"

### Details
![3](https://user-images.githubusercontent.com/22618677/58104430-5c87b380-7c17-11e9-8c5a-0410d32df343.png)
![4](https://user-images.githubusercontent.com/22618677/58104433-5e517700-7c17-11e9-965a-02a901fb413e.png)

**Comment by Crypto-APIs** [comment]
We fixed it.

**Comment by iborzenkov** [comment]
(+) Done
