### ISSUE TITLE
#031 "Create Payment" type mismatch in documentation and reality

### ISSUE THREAD

**Issue by iborzenkov** [iborzenkov/CryptoApisSdkLibrary#31]
### End Point 
BTC Create Payment
### URL
https://docs.cryptoapis.io/?http#btc-payment-forwarding-create-payment-endpoint
### Description
Parameter "fee" in documentation is a **number**. But in real server response it is a **string**. What's right?

### Details
![111](https://user-images.githubusercontent.com/22618677/58258298-13fe0080-7da5-11e9-96ed-48815917e6d3.png)

**Comment by Crypto-APIs** [comment]
The real sever response is correct. We have updated our documentation.

**Comment by Crypto-APIs** [comment]
@iborzenkov : Could you please check and close it in case it's fixed.

**Comment by iborzenkov** [comment]
(+) Fixed.
