### ISSUE TITLE
#005 "Historical Data" - unexpected server response

### ISSUE THREAD

**Issue by iborzenkov** [iborzenkov/CryptoApisSdkLibrary#5]
### End Point 
Historical Data
### URL
https://docs.cryptoapis.io/#historical-data
### Description
I expect that if the parameter "**time_start**" is a year from the future, there will be some error message. In fact, there is no error and returns an empty collection, as if everything is fine.

**Comment by Crypto-APIs** [comment]
From our perspective returning an empty collection is the correct behavior.

**Comment by iborzenkov** [comment]
(+) The current behavior is fixed in the tests
